name: rxdart_learning
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: nythrox <jasonsantiagobutler@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:  
  rxdart: ^0.22.2
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
